language: node_js
node_js:
- '8'
services:
- mongodb
after_success:
- scripts/coverage
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: pd-breja
  on:
    repo: eHattori/pd-breja
