#!/bin/bash

set -e

cd "$(dirname "$0")/.."

[ -z "$DEBUG" ] || set -x

export NODE_ENV="test"
scripts/setup

mkdir -p ./coverage

echo "===> Running coverage..."
# run the tests
./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha -- test/**/*.js --compilers js:babel-register 

# submit to coveralls
# enable coveralls

echo "===> Send to coveralls..."
./node_modules/.bin/coveralls < ./coverage/lcov.info
