#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

cd "$(dirname "$0")/.."

echo "===> Running migration..."
./node_modules/.bin/babel-node ./seeders/index.js

echo "===> Migration Complete..."



