#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

cd "$(dirname "$0")/.."

# ensure everything in the app is up to date.
scripts/update

if test -z "$NODE_ENV" && NODE_ENV='development' 
then
  echo "==> Execute in development mode."
  ./node_modules/.bin/pm2-dev ./src/app.js
else
  node process.js  
fi
