#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

cd "$(dirname "$0")/.."

scripts/bootstrap

if test -z "$NODE_ENV" && NODE_ENV='development' 
then
  echo "==> Execute in development mode."
  ./node_modules/.bin/pm2-dev --interpreter ./node_modules/.bin/babel-node ./src/app.js
else
  ./node_modules/.bin/babel-node process.js  
fi
