#!/bin/sh

# script/test: Run test suite for application. Optionally pass in a path to an
#              individual test file to run a single test.

set -e

cd "$(dirname "$0")/.."

[ -z "$DEBUG" ] || set -x

echo "===> Running linter..."

if [ -f "package.json" ]; then
  echo "==> Installing dev module dependencies…"
  npm install --only=dev
fi

./node_modules/semistandard/bin/cmd.js --fix

echo "===> Running tests..."
export NODE_ENV="test"
scripts/setup

./node_modules/.bin/_mocha --compilers js:babel-core/register test/**/*


