#!/bin/sh

# script/test: Run test suite for application. Optionally pass in a path to an
#              individual test file to run a single test.

set -e

cd "$(dirname "$0")/.."

scripts/setup

ls

[ -z "$DEBUG" ] || set -x

echo "===> Running linter..."

./node_modules/semistandard/bin/cmd.js

echo "===> Running tests..."
export NODE_ENV="test"

./node_modules/.bin/_mocha --compilers js:babel-core/register test/**/*


